# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.

name: Test

on: [push, pull_request]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    environment: AWS_EC2
    steps:
    - name: copy API via ssh key
      uses: appleboy/scp-action@v0.1.7
      with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "API_score_impaye.py"
          target: "./"

    - name: copy model pickle via ssh key
      uses: appleboy/scp-action@v0.1.7
      with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "mlflow_model/"
          target: "./"          

    - uses: actions/checkout@v2 
    - name: Lancement API sur le serveur AWS
      env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}} 
      run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "python3 API_score_impaye &&"
              # commande depuis le serveur AWS -- copie de l'API et model pickle 
    
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install local package
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Lancements Tests unitaires de l'API
    - name: Run tests
      run: python -m unittest
